name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v5
        with:
          version: 9.7.1
      - uses: actions/setup-node@v5
        with:
          node-version: 22.13.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm validate
